<a href="https://colab.research.google.com/github/byshadowoz/bsz/blob/main/Copia_de_Salarios_de_San_Francisco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTANDO Y DEFINIENDO DATAFRAME**

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from flask import Flask, request, jsonify

## **Dataframe de salarios en San francisco**

In [2]:
df = pd.read_csv('Salaries.csv', index_col=[0])

In [3]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
59229,Gwen Brister,Porter,51492.80,5322.74,624.00,27255.22,57439.54,84694.76,2012.0,NaN,San Francisco,NaN
59230,Shawn Sherburne,Manager III,57234.01,0.00,1500.00,25955.53,58734.01,84689.54,2012.0,NaN,San Francisco,NaN
59231,George Toy,Senior Clerk Typist,56125.73,0.00,855.00,27704.89,56980.73,84685.62,2012.0,NaN,San Francisco,NaN
59232,Henry Wong,Senior Clerk Typist,56237.00,0.00,288.00,28160.25,56525.00,84685.25,2012.0,NaN,San Francisco,NaN
59233,Dian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Limpieza de datos**

## Benefits tiene muchos datos Nan (Se remplaza con 0)

In [4]:
df.isna().sum()

EmployeeName            0
JobTitle                1
BasePay                 1
OvertimePay             1
OtherPay                1
Benefits            36160
TotalPay                1
TotalPayBenefits        1
Year                    1
Notes               59233
Agency                  1
Status              59233
dtype: int64

In [5]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
59229,Gwen Brister,Porter,51492.80,5322.74,624.00,27255.22,57439.54,84694.76,2012.0,NaN,San Francisco,NaN
59230,Shawn Sherburne,Manager III,57234.01,0.00,1500.00,25955.53,58734.01,84689.54,2012.0,NaN,San Francisco,NaN
59231,George Toy,Senior Clerk Typist,56125.73,0.00,855.00,27704.89,56980.73,84685.62,2012.0,NaN,San Francisco,NaN
59232,Henry Wong,Senior Clerk Typist,56237.00,0.00,288.00,28160.25,56525.00,84685.25,2012.0,NaN,San Francisco,NaN
59233,Dian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.Benefits.fillna(int(0), inplace=True)

## Eliminar columnas Notes y Status

In [7]:
df.isna().sum()

EmployeeName            0
JobTitle                1
BasePay                 1
OvertimePay             1
OtherPay                1
Benefits                0
TotalPay                1
TotalPayBenefits        1
Year                    1
Notes               59233
Agency                  1
Status              59233
dtype: int64

In [8]:
df.drop(columns=['Notes','Status'], axis=1, inplace=True)

## covertir objetos a Float

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59233 entries, 1 to 59233
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeName      59233 non-null  object
 1   JobTitle          59232 non-null  object
 2   BasePay           59232 non-null  float64
 3   OvertimePay       59232 non-null  float64
 4   OtherPay          59232 non-null  float64
 5   Benefits          59233 non-null  float64
 6   TotalPay          59232 non-null  float64
 7   TotalPayBenefits  59232 non-null  float64
 8   Year              59232 non-null  float64
 9   Agency            59232 non-null  object
dtypes: float64(7), object(3)
memory usage: 5.0+ MB

In [10]:
filas_a_eliminar = []

# Iterar sobre cada columna y encontrar las filas que contienen 'Not Provided'
for columna in df.columns:
    filas_a_eliminar.extend(df[df[columna] == 'Not Provided'].index)

# Eliminar las filas duplicadas de la lista
filas_a_eliminar = list(set(filas_a_eliminar))

# Eliminar las filas encontradas
df = df.drop(filas_a_eliminar)

# Mostrar el DataFrame resultante
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,0.00,567595.43,567595.43,2011.0,San Francisco
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,0.00,538909.28,538909.28,2011.0,San Francisco
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,0.00,335279.91,335279.91,2011.0,San Francisco
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,0.00,332343.61,332343.61,2011.0,San Francisco
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,0.00,326373.19,326373.19,2011.0,San Francisco
...,...,...,...,...,...,...,...,...,...,...
59229,Gwen Brister,Porter,51492.80,5322.74,624.00,27255.22,57439.54,84694.76,2012.0,San Francisco
59230,Shawn Sherburne,Manager III,57234.01,0.00,1500.00,25955.53,58734.01,84689.54,2012.0,San Francisco
59231,George Toy,Senior Clerk Typist,56125.73,0.00,855.00,27704.89,56980.73,84685.62,2012.0,San Francisco
59232,Henry Wong,Senior Clerk Typist,56237.00,0.00,288.00,28160.25,56525.00,84685.25,2012.0,San Francisco
59233,Dian,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN

In [11]:
columnas_a_convertir = ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']

# Convertir las columnas seleccionadas a tipo float
df[columnas_a_convertir] = df[columnas_a_convertir].astype(float)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59231 entries, 1 to 59233
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeName      59231 non-null  object
 1   JobTitle          59230 non-null  object
 2   BasePay           59230 non-null  float64
 3   OvertimePay       59230 non-null  float64
 4   OtherPay          59230 non-null  float64
 5   Benefits          59231 non-null  float64
 6   TotalPay          59230 non-null  float64
 7   TotalPayBenefits  59230 non-null  float64
 8   Year              59230 non-null  float64
 9   Agency            59230 non-null  object
dtypes: float64(7), object(3)
memory usage: 5.0+ MB

##Todas las Columnas ya fueron limpiadas

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59231 entries, 1 to 59233
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeName      59231 non-null  object
 1   JobTitle          59230 non-null  object
 2   BasePay           59230 non-null  float64
 3   OvertimePay       59230 non-null  float64
 4   OtherPay          59230 non-null  float64
 5   Benefits          59231 non-null  float64
 6   TotalPay          59230 non-null  float64
 7   TotalPayBenefits  59230 non-null  float64
 8   Year              59230 non-null  float64
 9   Agency            59230 non-null  object
dtypes: float64(7), object(3)
memory usage: 5.0+ MB

In [14]:
df.describe()

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,59230.000000,59230.000000,59230.000000,59231.000000,59230.000000,59230.000000,59230.000000
mean,74017.307427,5724.593344,4200.168276,14178.135433,83942.069047,98120.443854,2011.389532
std,39092.288718,11952.467443,8587.178979,18417.924109,46546.291412,56543.264460,0.487648
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2011.000000
25%,53728.970000,0.000000,28.747500,0.000000,58003.357500,59158.762500,2011.000000
50%,71610.580000,133.730000,1258.135000,0.000000,79900.765000,97018.100000,2011.000000
75%,100605.600000,6161.550000,5119.600000,33323.345000,112741.907500,132179.590000,2012.000000
max,302578.000000,245131.880000,400184.250000,84681.820000,567595.430000,567595.430000,2012.000000

In [15]:
titulos = df.value_counts(['JobTitle'])

In [16]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,0.00,567595.43,567595.43,2011.0,San Francisco
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,0.00,538909.28,538909.28,2011.0,San Francisco
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,0.00,335279.91,335279.91,2011.0,San Francisco
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,0.00,332343.61,332343.61,2011.0,San Francisco
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,0.00,326373.19,326373.19,2011.0,San Francisco
...,...,...,...,...,...,...,...,...,...,...
59229,Gwen Brister,Porter,51492.80,5322.74,624.00,27255.22,57439.54,84694.76,2012.0,San Francisco
59230,Shawn Sherburne,Manager III,57234.01,0.00,1500.00,25955.53,58734.01,84689.54,2012.0,San Francisco
59231,George Toy,Senior Clerk Typist,56125.73,0.00,855.00,27704.89,56980.73,84685.62,2012.0,San Francisco
59232,Henry Wong,Senior Clerk Typist,56237.00,0.00,288.00,28160.25,56525.00,84685.25,2012.0,San Francisco
59233,Dian,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN

### Pre Modelado

In [17]:
df_model = df.copy()

In [18]:
# se elimina EmployeeName y Agency por se incecesarios

df_model.drop(columns=['EmployeeName','Agency'], inplace=True)

In [22]:
df_model

,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
Id,,,,,,,,
1,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,0.0,567595.43,567595.43,2011
2,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,0.0,538909.28,538909.28,2011
3,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,0.0,335279.91,335279.91,2011
4,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,0.0,332343.61,332343.61,2011
5,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,0.0,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...
148646,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014
148648,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014
148649,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148654,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

In [19]:
from sklearn.preprocessing import OneHotEncoder

#Categóricas
cat = df_model.select_dtypes('O')

#Instanciamos
ohe = OneHotEncoder(sparse_output = False)

#Entrenamos
ohe.fit(cat)

#Aplicamos
cat_ohe = ohe.transform(cat)

#Ponemos los nombres
cat_ohe = pd.DataFrame(cat_ohe, columns = ohe.get_feature_names_out(input_features = cat.columns)).reset_index(drop = True)

In [24]:
cat_ohe

,JobTitle_ACCOUNT CLERK,JobTitle_ACCOUNTANT,JobTitle_ACCOUNTANT INTERN,"JobTitle_ACPO,JuvP, Juv Prob (SFERS)",JobTitle_ACUPUNCTURIST,JobTitle_ADMINISTRATIVE ANALYST,JobTitle_ADMINISTRATIVE ANALYST II,JobTitle_ADMINISTRATIVE ANALYST III,JobTitle_ADMINISTRATIVE ENGINEER,JobTitle_ADMINISTRATIVE SERVICES MANAGER,...,JobTitle_Window Cleaner Supervisor,JobTitle_Wire Rope Cable Maint Mechanic,JobTitle_Wire Rope Cable Maint Sprv,JobTitle_Worker's Comp Supervisor 1,JobTitle_Worker's Compensation Adjuster,JobTitle_X-RAY LABORATORY AIDE,JobTitle_X-Ray Laboratory Aide,"JobTitle_YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS",JobTitle_Youth Comm Advisor,JobTitle_ZOO CURATOR
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148646,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148647,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
df_model.drop(columns=['BasePay', 'OvertimePay', 'TotalPay','JobTitle', 'OtherPay'], inplace=True)

In [21]:
df_model = df_model.join(cat_ohe)

In [22]:
df_model = df_model.dropna()

In [29]:
df_model.isna().any()

Benefits                                                   False
TotalPayBenefits                                           False
Year                                                       False
JobTitle_ACCOUNT CLERK                                     False
JobTitle_ACCOUNTANT                                        False
                                                           ...
JobTitle_X-RAY LABORATORY AIDE                             False
JobTitle_X-Ray Laboratory Aide                             False
JobTitle_YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    False
JobTitle_Youth Comm Advisor                                False
JobTitle_ZOO CURATOR                                       False
Length: 2161, dtype: bool

In [23]:
x = df_model.drop(columns=['TotalPayBenefits'])
y = df_model.TotalPayBenefits

In [24]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [25]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [26]:
model.fit(x_train, y_train)

LinearRegression()

In [27]:
prediccion = model.predict(x_test)

In [28]:
prediccion

array([ 56854.30700111,  96978.41335779,  54887.76872456, ...,
        55136.93734109, 120634.8502301 , 175674.79016387])

In [29]:
y_test

Id
16725     72309.69
53379    105409.91
20913     60371.67
110      220744.85
19821     63772.91
           ...
22479     56202.80
21605     58613.31
29212     20984.54
49860    119802.63
40329    177575.47
Name: TotalPayBenefits, Length: 11846, dtype: float64

In [30]:
from sklearn.metrics import r2_score

r2_score(y_test, prediccion)

0.7990356008795958