<a href="https://colab.research.google.com/github/byshadowoz/bsz/blob/main/salarios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [42]:
df = pd.read_csv('/content/data_science_salaries.csv')
df

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,Large
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,Medium
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,Large
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,Large
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,Small

In [28]:
# cambiando nombre de datos employee_residence y company_location

In [43]:
df

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,Large
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,Medium
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,Large
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,Large
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,Small

In [44]:
dummie1 = pd.get_dummies(df['job_title'])
dummie2 = pd.get_dummies(df['experience_level'])
dummie3 = pd.get_dummies(df['employment_type'])
dummie4 = pd.get_dummies(df['work_models'])
dummie5 = pd.get_dummies(df['employee_residence'], prefix='er_')
dummie6 = pd.get_dummies(df['company_location'], prefix='cl_')
dummie7 = pd.get_dummies(df['company_size'], prefix='cs')

dummies = dummie1, dummie2,dummie3, dummie4, dummie5, dummie6, dummie7

In [46]:
#df = df.join(dummies)
df

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,...,cl__Thailand,cl__Turkey,cl__Ukraine,cl__United Arab Emirates,cl__United Kingdom,cl__United States,cl__Vietnam,cs_Large,cs_Medium,cs_Small
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,...,0,0,0,0,0,1,0,0,1,0
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,...,0,0,0,0,0,1,0,0,1,0
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,...,0,0,0,0,0,1,0,0,1,0
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,...,0,0,0,0,0,1,0,0,1,0
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6594,Staff Data Analyst,Entry-level,Contract,Hybrid,2020,Canada,60000,CAD,44753,Canada,...,0,0,0,0,0,0,0,1,0,0
6595,Staff Data Analyst,Executive-level,Full-time,On-site,2020,Nigeria,15000,USD,15000,Canada,...,0,0,0,0,0,0,0,0,1,0
6596,Machine Learning Manager,Senior-level,Full-time,Hybrid,2020,Canada,157000,CAD,117104,Canada,...,0,0,0,0,0,0,0,1,0,0
6597,Data Engineer,Mid-level,Full-time,Hybrid,2020,Austria,65000,EUR,74130,Austria,...,0,0,0,0,0,0,0,1,0,0
6598,Data Scientist,Senior-level,Full-time,On-site,2020,Austria,80000,EUR,91237,Austria,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
#eliminar columnas de donde se sacaron los dummies

In [52]:
df.drop(['job_title'], axis=1, inplace=True)
df.drop(['experience_level'], axis=1, inplace=True)
df.drop(['employment_type'], axis=1, inplace=True)
df.drop(['work_models'], axis=1, inplace=True)
df.drop(['employee_residence'], axis=1, inplace=True)
df.drop(['company_location'], axis=1, inplace=True)
df.drop(['company_size'], axis=1, inplace=True)
df.drop(['salary_currency'], axis=1, inplace=True)
df.drop(['salary'], axis=1, inplace=True)

In [ ]:
#modelo ML

In [53]:
x = df.drop(['salary_in_usd'], axis=1)
y = df['salary_in_usd']

model = LinearRegression()

In [54]:
from sklearn.model_selection import train_test_split

x_ent, x_pru, y_ent, y_pru = train_test_split(x, y, test_size=.2)

In [55]:
model.fit(x_ent, y_ent)

LinearRegression()

In [56]:
prediccion = model.predict(x_pru)

In [59]:
comparativa = {'prediccion': prediccion, 'valor real': y_pru}
pd.DataFrame(comparativa)

      prediccion  valor real
6345    119872.0      170000
291     123392.0      130000
4314    202304.0      155850
6571    129472.0       45618
5566     74048.0       64000
...          ...         ...
5297    130368.0       95000
1371    173056.0      136500
6517    109888.0       18907
3774    128896.0      116000
5754    162496.0      165000

[1320 rows x 2 columns]

In [60]:
model.score(x_ent, y_ent)

0.3841432504406499

In [62]:
df.corr()

,work_year,salary_in_usd,AI Architect,AI Developer,AI Engineer,AI Product Manager,AI Programmer,AI Research Engineer,AI Scientist,AWS Data Architect,...,cl__Thailand,cl__Turkey,cl__Ukraine,cl__United Arab Emirates,cl__United Kingdom,cl__United States,cl__Vietnam,cs_Large,cs_Medium,cs_Small
work_year,1.000000,0.155993,0.033576,0.009765,0.033602,0.003312,0.000665,-0.000753,-0.050673,0.003312,...,-0.015333,-0.033401,0.008116,-0.046939,-0.023247,0.194581,0.005738,-0.321397,0.409381,-0.245441
salary_in_usd,0.155993,1.000000,0.047500,-0.003258,0.020580,-0.004436,-0.033244,-0.031860,-0.024400,0.019512,...,-0.036853,-0.047839,-0.010302,-0.013696,-0.154382,0.336531,-0.023316,-0.107915,0.162699,-0.132657
AI Architect,0.033576,0.047500,1.000000,-0.002037,-0.003335,-0.000480,-0.001175,-0.001073,-0.002253,-0.000480,...,-0.000831,-0.001073,-0.001175,-0.000831,-0.010001,0.018786,-0.000831,0.015791,-0.010873,-0.006335
AI Developer,0.009765,-0.003258,-0.002037,1.000000,-0.004477,-0.000644,-0.001578,-0.001440,-0.003025,-0.000644,...,-0.001115,-0.001440,0.287623,-0.001115,-0.013426,-0.056470,-0.001115,0.004637,-0.036709,0.064856
AI Engineer,0.033602,0.020580,-0.003335,-0.004477,1.000000,-0.001054,-0.002582,-0.002357,-0.004951,-0.001054,...,-0.001826,-0.002357,-0.002582,-0.001826,0.007643,-0.008861,-0.001826,-0.007235,0.007778,-0.002663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cl__United States,0.194581,0.336531,0.018786,-0.056470,-0.008861,-0.025530,-0.062559,-0.043027,-0.066182,0.005937,...,-0.044226,-0.057104,-0.062559,-0.044226,-0.532358,1.000000,-0.044226,-0.177520,0.246356,-0.175853
cl__Vietnam,0.005738,-0.023316,-0.000831,-0.001115,-0.001826,-0.000263,-0.000643,-0.000587,-0.001233,-0.000263,...,-0.000455,-0.000587,-0.000643,-0.000455,-0.005475,-0.044226,1.000000,-0.006551,0.007573,-0.003468
cs_Large,-0.321397,-0.107915,0.015791,0.004637,-0.007235,0.040077,0.026557,0.030782,0.057159,0.040077,...,0.044100,0.030782,-0.009267,0.018775,-0.022819,-0.177520,-0.006551,1.000000,-0.865016,-0.049952
cs_Medium,0.409381,0.162699,-0.010873,-0.036709,0.007778,-0.034667,-0.053062,-0.025150,-0.104508,-0.034667,...,-0.037512,-0.042614,-0.005231,-0.060055,0.021330,0.246356,0.007573,-0.865016,1.000000,-0.457909
cs_Small,-0.245441,-0.132657,-0.006335,0.064856,-0.002663,-0.002002,0.058568,-0.004478,0.106755,-0.002002,...,-0.003468,0.030286,0.026831,0.086277,-0.002028,-0.175853,-0.003468,-0.049952,-0.457909,1.000000